name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Update
      run: sudo apt-get update && sudo apt-get upgrade
    - name: Install SDL2
      run: sudo apt-get install libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev
    - name: make check
      run: make check
    - name: make all
      run: make all
        #- name: make test
        #run: make test
